spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/money_manager
    driverClassName: org.postgresql.Driver
    password: postgres
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update